parameters:
# nothing to declare

services:
  _defaults:
    autowire: true

  LeoVie\PhpMethodRunner\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/PhpMethodRunnerBundle.php'

  LeoVie\PhpMethodRunner\Configuration\Configuration: ~

directories:
  template_directory: ../template/
  generated_directory: ../generated/